### ISSUE TITLE
Input is glitchy.

### ISSUE THREAD

**Issue by anoduck** [abhshkdz/HackFlowy#35]
When I installed it I immediately ran into a sqlite error

``` shell
Unhandled rejection SequelizeBaseError: SQLITE_BUSY: database is locked
    at Query.formatError (/path/to/HackFlowy/node_modules/sequelize/lib/dialects/sqlite/query.js:345:14)
    at Statement.afterExecute (/path/to/HackFlowy/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/path/to/HackFlowy/node_modules/sqlite3/lib/trace.js:19:31)

Unhandled rejection SequelizeBaseError: SQLITE_BUSY: database is locked
    at Query.formatError (/path/to/HackFlowy/node_modules/sequelize/lib/dialects/sqlite/query.js:345:14)
    at Statement.afterExecute (/path/to/HackFlowy/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/path/to/HackFlowy/node_modules/sqlite3/lib/trace.js:19:31)

Unhandled rejection SequelizeBaseError: Validation error
    at Query.formatError (/path/to/HackFlowy/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/path/to/HackFlowy/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/path/to/HackFlowy/node_modules/sqlite3/lib/trace.js:19:31)
```
which was odd...

Once I opened the browser I was unable to type more than two letters without various glitches occurring, from my cursor disappearing to the browser jumping to the bottom of the page. Whatever was typed would remain together in a block of text, but once reloaded would sometimes disappear and other times an additional node would appear either below or above. Also it appeared that all edits were persistent, meaning that once the browser was reloaded whatever was at one time deleted now reappears with sometimes an added node attached either above or below. 

The sqlite3 errors and browser glitches might not be correlated at all. Wish I could be more of an assistance. This is quite a cool little app to have handy.

**Comment by desyncr** [comment]
We do have some glitches here and there. I'm not sure about the database error. Are you running this on heroku or local? I haven't seen that error before.

**Comment by anoduck** [comment]
It is a local install. AND, I just ran it with both the debug flag on and off, and I did not receive that error again. Still glitchy, but a great little application nonetheless. I believed something must have resolved the issue. It must have been your mysterious magical coding powers, working their magic over the net. IDK... :)
